# Generated by Django 3.0.3 on 2020-03-05 21:36

from django.db import migrations


create_items = """
        CREATE TABLE `hyper_items` (
            `cid` smallint unsigned NOT NULL COMMENT 'IID of the category this item belongs to; must be in <0,65535> range',
            `iid` bigint unsigned NOT NULL COMMENT 'IID (Item ID) of this item; unique within its category only',
            `data` json NOT NULL,
            
            -- 2 fractional digits in timestamps to record time with precision of 1/100 sec,
            -- each timestamp value occupies 4B + 1B for fractional part
            `created` timestamp(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),
            `updated` timestamp(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2) ON UPDATE CURRENT_TIMESTAMP(2),
            PRIMARY KEY (`cid`,`iid`)
        ) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin ROW_FORMAT=COMPRESSED        
        """

create_items_revert = "DROP TABLE hyper_items;"


#####################################################################################################################################################

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(create_items, create_items_revert),        
    ]
