# Generated by Django 3.0.3 on 2020-03-05 21:36

from django.db import migrations


create_items = """
        CREATE TABLE hyperweb_items
        (
            id BIGINT UNSIGNED NOT NULL,
            data JSON NOT NULL,
            
            -- 2 fractional digits in timestamps to record time with precision of 1/100 sec,
            -- each timestamp value occupies 4B + 1B for fractional part
            created TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),
            updated TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2) ON UPDATE CURRENT_TIMESTAMP(2),

            CONSTRAINT items_pk PRIMARY KEY (id)
            
        ) ENGINE=InnoDB ROW_FORMAT=COMPRESSED;
        """

create_items_revert = "DROP TABLE hyperweb_items;"


#####################################################################################################################################################

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(create_items, create_items_revert),        
    ]
