#
# Startup configuration of the local Schemat process
#

# ID of the Site object to be loaded at startup
site: 1004

# bootstrap_database:
# Configuration of a temporary database from which the Site and the main Database are loaded during startup.
# One of the rings should contain the target Site object together with its immediate dependencies (e.g., database).
# After the Site and its ultimate Database are loaded, the bootstrap database is discarded.
# Each bootstrap ring is read-only if not declared otherwise (`readonly: false`).

bootstrap_database:
  rings:
    - file: ./data/db-boot.yaml                    # core categories; practically immutable (very rarely changed)
    - file: ./data/db-base.yaml
    - file: ./data/db-cluster.yaml                 # physical layer: nodes, rings, database
    - file: ./data/db-site.yaml                    # logical layer: site, system folders, system objects
    #- file: ../app-demo/data/db-paperity.yaml
