#
# Startup configuration of the local Schemat process
#

# ID of the Cluster that this node is, or should be, a part of
cluster: 1025


# bootstrap_rings:
# Configuration of a temporary database from which the Application, the Cluster, and the main Database are loaded during startup.
# One of the rings should contain the target Application object together with its immediate dependencies (e.g., database).
# After the Application and its ultimate Database are loaded, the bootstrap database is discarded.
# Each bootstrap ring is read-only if not declared otherwise (`readonly: false`), but this declaration is temporary
# and only affects the bootstrap phase. The final configuration of rings is read from the ultimate database, and for
# this reason, the bootstrap database typically consists of just the kernel ring and the cluster/app configuration ring.

bootstrap_rings:
  - name: boot_kernel
    file: ./schemat/data/00_kernel.data.yaml
  - name: boot_cluster
    file: ./demo/01_books/_data/01_cluster.data.yaml
